name: build

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:

jobs:
    test_aplication:
      runs-on: ubuntu-latest

      steps:
      - name: Imagine uma linda build
        run: |
            sleep 70
            echo "Build concluida"