name: CI Workflow

on: [push]

jobs:
  teste_1:
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/test_1.yml@main
  
  teste_2:
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/test_2.yml@main
    secrets: inherit

  teste_3:
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/test_3.yml@main

  teste_4:
    needs: [teste_1, teste_3]
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/test_4.yml@main

  build:
    needs: [teste_1, teste_2, teste_3, teste_4]
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/build.yml@main

  deploy:
    needs: build
    uses: AlanwMelo/feegow-challenge-qa-engineer/.github/workflows/deploy.yml@main