name: teste_4

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:

jobs:
    test_aplication:
      runs-on: ubuntu-latest

      steps:
        - name: Baixa o Log gerado no teste 1
          uses: actions/download-artifact@v4

        - name: Lista artefato
          run:  ls