name: lint_validator

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:

jobs:
    test_aplication:
        runs-on: ubuntu-latest
        steps:
        # Configura o container para ter o python instalado
        - name: Instala o python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12.3'
        
        - name: Clona o repositorio
          uses: actions/checkout@v2
        
        - name: Configuta o Robot e o Selenium
          run: |
            python3 -m pip install --upgrade pip
            pip install selenium
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install robotframework-requests
            
        - name: Test
          run: |
            cd /home/runner/work/feegow-challenge-qa-engineer/feegow-challenge-qa-engineer
            robot ./2.automation-tests/alan/agendamento_cancelamento.robot

        - name: Salva o log do robot
          uses: actions/upload-artifact@v3
          with:
            name: robot_log.html
            path: ./2.automation-tests/alan/log.html