name: teste_2

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:

jobs:
    test_aplication:
      runs-on: ubuntu-latest
    
      steps:          
        - name: Exemplo de teste 2
          env:
            my_name: ${{ secrets.MY_NAME_IS }}
          run: |
            echo " Its a me $my_name"

            if [ "$my_name" = "AlanWMelo" ]; then
                echo "E meu nome mesmo"
            else
                echo "Nao e"
            fi

            sleep 20
            echo "Teste 2 concluido"