name: teste_2

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:
      secrets: 
        MY_NAME:
          required: true

jobs:
    test_aplication:
      runs-on: ubuntu-latest
      steps:          
        - name: Exemplo de teste 2
          run: |
            echo " Its a me ${{ secrets.MY_NAME }}"

            if [ "${{ secrets.MY_NAME }}" = "AlanWMelo" ]; then
                echo "E meu nome mesmo"
            else
                echo "Nao e"
            fi

            sleep 20
            echo "Teste 2 concluido"