name: teste_3

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:

jobs:
    test_aplication:
      runs-on: ubuntu-latest

      steps:
      - name: Exemplo de teste 3
        uses: |
            sleep 45
            echo "Teste 3 concluido"