name: teste_3

on:
    # Este evento permite que o workflow seja chamado por outros workflows
    workflow_call:
      
env: 
  VAR_TESTE_3: "Variavel global do teste 3"

jobs:
    test_aplication:
      runs-on: ubuntu-latest

      steps:
      - name: Exemplo de teste 3
        id: step1
        run: |
            sleep 18
            echo "$VAR_TESTE_3 no 3"
            echo "Teste 3 concluido"

      - name: Exemplo de teste 3.5
        id: step2
        run: |
            sleep 18
            echo "$VAR_TESTE_3 no 3.5"
            echo "Teste 3.5 concluido"